apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
    name: bookstack
    labels:
        manager: kubero
spec:
    name: bookstack
    deploymentstrategy: docker
    envVars:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: Etc/UTC
        - name: APP_URL
          value: http://bookstack.example.com
        - name: APP_KEY
          value: base64:dm1hdnZvbmdvaDhxcTlnZXZkeXVzdmU4MnRnaWlhcDg=
        - name: DB_HOST
          value: bookstack-mysql
        - name: DB_PORT
          value: "3306"
        - name: DB_USERNAME
          value: bookstack
        - name: DB_PASSWORD
          value: bookstack
        - name: DB_DATABASE
          value: bookstack
    web:
        replicaCount: 1
    worker:
        replicaCount: 0
    image:
        containerPort: "80"
        pullPolicy: Always
        repository: lscr.io/linuxserver/bookstack
        tag: latest
    extraVolumes: []
    cronjobs: []
    addons:
        - displayName: MySQL
          env: []
          icon: /img/addons/mysql.svg
          id: kubero-operator
          kind: KuberoMysql
          resourceDefinitions:
              KuberoMysql:
                  apiVersion: application.kubero.dev/v1alpha1
                  kind: KuberoMysql
                  metadata:
                      name: bookstack-mysql
                  spec:
                      mysql:
                          auth:
                              createDatabase: true
                              database: bookstack
                              password: bookstack
                              rootPassword: bookstack
                              username: bookstack
                          global:
                              storageClass: standard
                          primary:
                              persistence:
                                  accessModes:
                                      - ReadWriteOnce
                                  size: 1Gi
          version:
              latest: 0.1.5