name: Moodist
description: 'Ambient sounds for focus and calm.'
tags:
- tools
source: https://github.com/remvze/moodist
website: https://moodist.app/
icon: https://moodist.app/logo.svg
documentation:
screenshots:
