name: SQLPad
description: 'SQLPad is a web-based SQL editor that allows you to write queries, visualize data, and share your results.'
tags:
- tools
- database
source: https://github.com/sqlpad/sqlpad
website: https://getsqlpad.com/
icon: https://avatars.githubusercontent.com/u/67432073?s=48&v=4
screenshots:
- https://user-images.githubusercontent.com/303966/99915755-32f78e80-2ccb-11eb-9f74-b18846d6108d.png