apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
    name: it-tools
    labels:
        manager: kubero
spec:
    name: it-tools
    deploymentstrategy: docker
    envVars: []
    extraVolumes: []
    cronjobs: []
    addons: []
    web:
        replicaCount: 1
    worker:
        replicaCount: 0
    image:
        containerPort: "80"
        pullPolicy: Always
        repository: corentinth/it-tools
        tag: latest
