name: Keila
description: 'Open Source Newsletter Tool.'
tags:
- newsletter
source: https://github.com/pentacent/keila
website: https://keila.io/
icon: https://raw.githubusercontent.com/pentacent/keila/main/.github/assets/logo.svg
documentation: https://www.keila.io/docs/configuration
screenshots:
- https://raw.githubusercontent.com/pentacent/keila/main/.github/assets/keila-20211203.jpg