name: Fief
description: 'Users and authentication management'
tags:
- security
- authentication
source: https://github.com/fief-dev/fief
website: https://www.fief.dev
icon: https://avatars.githubusercontent.com/u/97037414?s=200&v=4
documentation: https://docs.fief.dev
screenshots:
- https://www.fief.dev/illustrations/signin.png