apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
    name: rsshub
    labels:
        manager: kubero
spec:
    name: rsshub
    deploymentstrategy: docker
    envVars: []
    extraVolumes: []
    cronjobs: []
    addons: []
    web:
        replicaCount: 1
    worker:
        replicaCount: 0
    image:
        containerPort: "1200"
        pullPolicy: Always
        repository: diygod/rsshub
        tag: chromium-bundled
