kubero:
  context: kind-kubero
  namespace: kubero
  port: 3000
buildpacks:
  - name: NodeJS
    language: JavaScript
    repositories:
      fetch:
        image: ghcr.io/kubero-dev/docker-images/base
        tag: main
      build:
        image: node
        tag: latest
      run:
        image: node
        tag: latest
  - name: PHP
    language: PHP
    repositories:
      fetch:
        image: ghcr.io/kubero-dev/docker-images/base
        tag: main
      build:
        image: composer
        tag: latest
      run:
        image: webdevops/php-apache
        tag: "8.1"
  - name: Python
    language: Python
    repositories:
      fetch:
        image: ghcr.io/kubero-dev/docker-images/base
        tag: main
      build:
        image: python
        tag: 3.10-buster
      run:
        image: python
        tag: 3.10-buster
  - name: Go
    language: goLang
    repositories:
      fetch:
        image: ghcr.io/kubero-dev/docker-images/base
        tag: main
      build:
        image: golang
        tag: alpine
      run:
        image: golang
        tag: alpine
  - name: Python
    language: goLang
    repositories:
      fetch:
        image: ghcr.io/kubero-dev/docker-images/base
        tag: main
      build:
        image: golang
        tag: alpine
      run:
        image: golang
        tag: alpine
  - name: Ruby
    language: Ruby
    repositories:
      fetch:
        image: ghcr.io/kubero-dev/docker-images/base
        tag: main
      build:
        image: ruby
        tag: "2.7"
      run:
        image: ruby
        tag: "2.7"
  - name: Static
    language: HTML
    repositories:
      fetch:
        image: ghcr.io/kubero-dev/docker-images/base
        tag: main
      build:
        image: busybox
        tag: latest
      run:
        image: webdevops/nginx
        tag: alpine
podSizeList: 
- name: small
  description: 'Small (CPU: 0.25, Memory: 0.5Gi)'
  default: true
  resources:
    requests:
      memory: 0.5Gi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m
- name: medium
  description: 'Medium (CPU: 1, Memory: 2Gi)'
  resources:
    requests:
      memory: 2Gi
      cpu: 1000m
    limits:
      memory: 4Gi
      cpu: 2000m
- name: large
  description: 'Large (CPU: 2, Memory: 4Gi)'
  active: false
  resources:
    requests:
      memory: 4Gi
      cpu: 2000m
