kubero:
  context: kind-kubero
  namespace: kubero
  port: 3000
buildpacks:
  - name: NodeJS
    language: JavaScript
    fetch:
      repository: ghcr.io/kubero-dev/buildpacks/fetch
      tag: main
    build:
      repository: node
      tag: latest
    run:
      repository: node
      tag: latest
  - name: PHP
    language: PHP
    fetch:
      repository: ghcr.io/kubero-dev/buildpacks/fetch
      tag: main
    build:
      repository: composer
      tag: latest
    run:
      repository: ghcr.io/kubero-dev/buildpacks/php
      tag: "main"
      readOnlyAppStorage: false
      securityContext:
        allowPrivilegeEscalation: true
        readOnlyRootFilesystem: false
  - name: PHP-testing
    language: PHP
    fetch:
      repository: ghcr.io/kubero-dev/buildpacks/fetch
      tag: main
    build:
      repository: composer
      tag: latest
    run:
      repository: webdevops/php-apache
      tag: "8.1"
      readOnlyAppStorage: false
      securityContext:
        allowPrivilegeEscalation: true
        readOnlyRootFilesystem: false
  - name: Python
    language: Python
    fetch:
      repository: ghcr.io/kubero-dev/buildpacks/fetch
      tag: main
    build:
      repository: python
      tag: 3.10-buster
    run:
      repository: python
      tag: 3.10-buster
  - name: GoLang
    language: GoLang
    fetch:
      repository: ghcr.io/kubero-dev/buildpacks/fetch
      tag: main
    build:
      repository: golang
      tag: alpine
    run:
      repository: golang
      tag: alpine
  - name: Python
    language: goLang
    fetch:
      repository: ghcr.io/kubero-dev/buildpacks/fetch
      tag: main
    build:
      repository: golang
      tag: alpine
    run:
      repository: golang
      tag: alpine
  - name: Ruby
    language: Ruby
    fetch:
      repository: ghcr.io/kubero-dev/buildpacks/fetch
      tag: main
    build:
      repository: ruby
      tag: "2.7"
    run:
      repository: ruby
      tag: "2.7"
  - name: Static
    language: HTML
    fetch:
      repository: ghcr.io/kubero-dev/buildpacks/fetch
      tag: main
    build:
      repository: busybox
      tag: latest
    run:
      repository: webdevops/nginx
      tag: alpine
podSizeList: 
- name: small
  description: 'Small (CPU: 0.25, Memory: 0.5Gi)'
  default: true
  resources:
    requests:
      memory: 0.5Gi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m
- name: medium
  description: 'Medium (CPU: 1, Memory: 2Gi)'
  resources:
    requests:
      memory: 2Gi
      cpu: 1000m
    limits:
      memory: 4Gi
      cpu: 2000m
- name: large
  description: 'Large (CPU: 2, Memory: 4Gi)'
  active: false
  resources:
    requests:
      memory: 4Gi
      cpu: 2000m
