kubero:
  context: kind-kubero
  namespace: kubero
  port: 3000
buildpacks:
  - name: NodeJS
    web:
      repository: ghcr.io/kubero-dev/docker-images/node-web
      tag: main
    builder:
      repository: ghcr.io/kubero-dev/docker-images/node-builder
      tag: main
  - name: Python
    web:
      repository: ghcr.io/kubero-dev/docker-images/python-web
      tag: main
    builder:
      repository: ghcr.io/kubero-dev/docker-images/python-builder
      tag: main
  - name: PHP
    web:
      repository: ghcr.io/kubero-dev/docker-images/php-web
      tag: main
    builder:
      repository: ghcr.io/kubero-dev/docker-images/php-builder
      tag: main
  - name: Go
    web:
      repository: ghcr.io/kubero-dev/docker-images/go-web
      tag: main
    builder:
      repository: ghcr.io/kubero-dev/docker-images/go-builder
      tag: main
  - name: Scala
    web:
      repository: ghcr.io/kubero-dev/docker-images/scala-web
      tag: main
    builder:
      repository: ghcr.io/kubero-dev/docker-images/scala-builder
      tag: main
  - name: Ruby
    web:
      repository: ghcr.io/kubero-dev/docker-images/ruby-web
      tag: main
    builder:
      repository: ghcr.io/kubero-dev/docker-images/ruby-builder
      tag: main
podSizeList: 
- name: small
  description: 'Small (CPU: 0.25, Memory: 0.5Gi)'
  default: true
  resources:
    requests:
      memory: 0.5Gi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m
- name: medium
  description: 'Medium (CPU: 1, Memory: 2Gi)'
  resources:
    requests:
      memory: 2Gi
      cpu: 1000m
    limits:
      memory: 4Gi
      cpu: 2000m
- name: large
  description: 'Large (CPU: 2, Memory: 4Gi)'
  active: false
  resources:
    requests:
      memory: 4Gi
      cpu: 2000m
