services:
  # Kubero usually runs in a Kubernetes cluster in the kubero namespace
  # If you want to run it locally, you can use kind to create a local Kubernetes cluster
  # 1) Find your cluster name [YOUR_CLUSTER_NAME] by running `kind get clusters`
  # 2) Set the cluster name in the YOUR_CLUSTER_NAME environment variable `export YOUR_CLUSTER_NAME=...`
  # 3) run `kind get kubeconfig --name ${YOUR_CLUSTER_NAME} > ./kubeconfig` to get the right config
  # 4) replace localhost with the IP of your host machine in the extra_hosts section `sed -i'' -e "s/127.0.0.1/${YOUR_CLUSTER_NAME}-control-plane/g" ./kubeconfig`
  kubero:
    container_name: "kubero-ui"
    build:
      context: .
      args:
        - VERSION=Local-Build
      dockerfile: Dockerfile
    image: ghcr.io/kubero-dev/kubero/kubero:latest
    #command: ["tail", "-f", "/dev/null"]
    env_file:
      # copy the .env.template file to .env and change the values to your needs
      - server/.env
    environment:
      # change the KUBERO_CONTEXT to the name of your local kind cluster context
      # you can find the name by running `kubectl config get-contexts`
      # Must be the same as the context name in the kubeconfig file !
      #- KUBECONFIG_BASE64=
      - KUBECONFIG_PATH=./kubeconfig
      - KUBERO_CONTEXT=kind-${YOUR_CLUSTER_NAME}
      - KUBERO_NAMESPACE=kubero
      - KUBERO_SESSION_KEY=randomString
    ports:
      # the UI will be available on http://localhost:8000. Make sure the port is not used by another service
      - "8000:2000"
    extra_hosts:
      # if you are using a local Kubernetes cluster, make sure you use the container name from your 
      # local kind cluster control plane. You can find the name by running `docker ps` and looking for the
      # container name of the control plane. 192.168.65.254 is your host machine IP address.
      - "${YOUR_CLUSTER_NAME}-control-plane:192.168.65.254"
    volumes:
      - ./kubeconfig:/app/server/kubeconfig
      - ./server/config.yaml:/app/server/config.yaml
      - ./server/db:/app/server/db