version: "3.9"  # optional since v1.27.0
services:
  kubero:
    container_name: "kubero"
    build: .
    #command: ["tail", "-f", "/dev/null"]
    env_file:
      - .env
    ports:
      - "8000:2000"
    extra_hosts:
      - "kubero-control-plane:192.168.65.2"
    volumes:
      #- .:/app
      - ./kubeconfig-docker:/app/server/kubeconfig
      - ./config.yaml:/app/server/config.yaml
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ./.dockerdata/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"