version: "3"
services:
  kubero:
    container_name: "kubero"
    build: .
    image: ghcr.io/kubero-dev/kubero/kubero:latest
    env_file:
      - .env
    environment:
      - KUBERO_CONTEXT=kind-kubero-noolm # make sure you use the context name from your mounted kubeconfig
    ports:
      - "8000:2000"
    extra_hosts:
      - "kind-kubero-noolm-control-plane:192.168.65.2" # make sure you use the container name from your local kind cluster control plane
    volumes:
      #- .:/app
      - ./kubeconfig-docker:/app/server/kubeconfig # change the port 6443 to the outside port of your local kind cluster control plane
      - ./config.yaml:/app/server/config.yaml