site_name: Kubero Documentation
theme:
  name: readthedocs
  highlightjs: true
plugins:
  #- search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
#nav:
#    - 'Home': 'index.md'
#    - '1quickstart.md'
#    - '2screenshots.md'
#    - '3comparison.md'
#    - 'Installation':
#      - 'Prerequisites': '1prerequisites.md'
#      - 'Getting Started': '2base.md'
#      - 'Authentication': 3authentication.md
#      - 'Configuration': 4configuration.md
#    - 'User manual':
#      - 'Buildpacks': 'buildpacks.md'
#      - 'Deployment': deployment.md
#      - 'Services': services.md
#    - 'Developer manual':
#      - 'Setup': 'setup.md'
      #- 'architecture.md'
      #- 'development.md'
      #- 'testing.md'
      #- 'release.md'
      #- 'deployment.md'
      #- 'changelog.md'