apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
    name: daily-stars-explorer
    labels:
        manager: kubero
spec:
    name: daily-stars-explorer
    deploymentstrategy: docker
    envVars:
        - name: HOST
          value: 0.0.0.0
        - name: PAT
          value: CHANGE-ME
        - name: PAT2
          value: CHANGE-ME
        - name: REDDIT_CLIENT_ID
          value: CHANGE-ME
        - name: REDDIT_CLIENT_SECRET
          value: CHANGE-ME
        - name: REDDIT_USER_AGENT
          value: CHANGE-ME
        - name: REDDIT_USERNAME
          value: CHANGE-ME
        - name: REDDIT_PASSWORD
          value: CHANGE-ME
        - name: YOUTUBE_API_KEY
          value: CHANGE-ME
    extraVolumes: []
    cronjobs: []
    addons: []
    web:
        replicaCount: 1
    worker:
        replicaCount: 0
    image:
        containerPort: 8080
        pullPolicy: Always
        repository: ghcr.io/emanuelef/daily-stars-explorer
        tag: latest