apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: grafana
spec:
  name: grafana
  domain: grafana.lacolhost.com
  deploymentstrategy: docker
  image:
    repository: grafana/grafana-enterprise
    tag: latest
    containerPort: "3000"
  ingress:
    hosts:
    - host: grafana.lacolhost.com
      paths:
      - path: /
        pathType: ImplementationSpecific
  addons: []
  envVars:
  - name: GF_INSTALL_PLUGINS
    value: grafana-clock-panel,grafana-simple-json-datasource
  cronjobs: []
  extraVolumes:
  - accessModes:
    - ReadWriteMany
    emptyDir: false
    mountPath: /var/lib/grafana
    name: grafana-data
    size: 1Gi
    storageClass: standard
  web:
    replicaCount: 1
  worker:
    replicaCount: 0