name: wordpress
description: ''
tags:
- Search
source: https://github.com/WordPress/WordPress
website: https://github.com/benbusby/whoogle-search
icon: https://www.freeiconspng.com/uploads/question-answer-icon-14.png
screenshots:
- https://raw.githubusercontent.com/benbusby/whoogle-search/main/docs/screenshot_desktop.png
- https://raw.githubusercontent.com/benbusby/whoogle-search/main/docs/screenshot_mobile.png
