name: wordpress
description: 'WordPress is a free and open-source content management system written in hypertext preprocessor language and paired with a MySQL or MariaDB database with supported HTTPS.'
tags:
- Search
source: https://github.com/WordPress/WordPress
website: https://github.com/benbusby/whoogle-search
icon: https://avatars.githubusercontent.com/u/276006?s=280
screenshots:
- https://raw.githubusercontent.com/benbusby/whoogle-search/main/docs/screenshot_desktop.png
- https://raw.githubusercontent.com/benbusby/whoogle-search/main/docs/screenshot_mobile.png
