name: Leantime
description: 'Leantime is a goals focused project management system for non-project managers. Building with ADHD, Autism, and dyslexia in mind.'
tags:
- project-management
source: https://github.com/Leantime/leantime
website: https://leantime.io/
icon: https://avatars.githubusercontent.com/u/11252321?s=200&v=4
screenshots:
- https://raw.githubusercontent.com/Leantime/leantime/master/public/assets/images/Screenshots/mywork.png
- https://raw.githubusercontent.com/Leantime/leantime/master/public/assets/images/Screenshots/dark.png
- https://raw.githubusercontent.com/Leantime/leantime/master/public/assets/images/Screenshots/kanban.png
- https://raw.githubusercontent.com/Leantime/leantime/master/public/assets/images/Screenshots/timeline.png