name: pgAdmin
description: 'pgAdmin is the most popular and feature rich Open Source administration and development platform for PostgreSQL.'
tags:
- database
source: https://github.com/pgadmin-org/pgadmin4
website: https://www.pgadmin.org
icon: https://raw.githubusercontent.com/TwiN/gatus/9e46e3972d382c62ebf954eb109b3c856d33bd58/web/app/public/logo-192x192.png
screenshots: