name: pgAdmin
description: 'pgAdmin is the most popular and feature rich Open Source administration and development platform for PostgreSQL.'
tags:
- database
source: https://github.com/pgadmin-org/pgadmin4
website: https://www.pgadmin.org
icon: https://avatars.githubusercontent.com/u/113517144?s=200&v=4
screenshots:
