name: Stirling PDF
description: 'Stirling PDF is a hosted web application that allows you to perform various operations on PDF files, such as splitting and adding images.'
tags:
- PDF
source: https://github.com/Frooodle/Stirling-PDF
website: https://github.com/Frooodle/Stirling-PDF
icon: https://raw.githubusercontent.com/Frooodle/Stirling-PDF/main/docs/stirling.png
screenshots:
- https://raw.githubusercontent.com/Frooodle/Stirling-PDF/main/images/stirling-home.png