apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
    name: searxng
    annotations:
        kubero.dev/template.architecture: '["linux/amd64", "linux/arm64", "linux/arm/v7"]'
        kubero.dev/template.description: "SearXNG is a free internet metasearch engine which aggregates results from various search services and databases. Users are neither tracked nor profiled."
        kubero.dev/template.icon: "https://avatars.githubusercontent.com/u/80454229"
        kubero.dev/template.installation: ""
        kubero.dev/template.links: "[]"
        kubero.dev/template.screenshots: "[]"
        kubero.dev/template.source: "https://github.com/searxng/searxng"
        kubero.dev/template.categories: '["utility"]'
        kubero.dev/template.title: "searxng"
        kubero.dev/template.website: "https://docs.searxng.org/"
    labels:
        manager: kubero
spec:
    name: searxng
    deploymentstrategy: docker
    envVars:
        - name: BASE_URL
          value: https://searxng.localhost/
        - name: INSTANCE_NAME
          value: example
    extraVolumes:
        - accessMode: ReadWriteOnce
          accessModes:
              - ReadWriteOnce
          emptyDir: false
          mountPath: /etc/searxng
          name: searxng-volume
          size: 1Gi
          storageClass: standard
    cronjobs: []
    addons: []
    web:
        replicaCount: 1
    worker:
        replicaCount: 0
    image:
        containerPort: 8080
        pullPolicy: Always
        repository: searxng/searxng
        tag: latest
