apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
    name: kimai
    annotations:
        kubero.dev/template.architecture: '["linux/amd64", "linux/arm64"]'
        kubero.dev/template.description: "Kimai is a web-based multi-user time-tracking application. Works great for everyone: freelancers, companies, organizations"
        kubero.dev/template.icon: "https://avatars.githubusercontent.com/u/981996"
        kubero.dev/template.installation: ""
        kubero.dev/template.links: "[]"
        kubero.dev/template.screenshots: "[]"
        kubero.dev/template.source: "https://github.com/kimai/kimai"
        kubero.dev/template.categories: '["work", "productivity"]'
        kubero.dev/template.title: "Kimai"
        kubero.dev/template.website: "https://www.kimai.org"
    labels:
        manager: kubero
spec:
    name: kimai
    deploymentstrategy: docker
    envVars:
        - name: ADMINMAIL
          value: admin@kimai.local
        - name: ADMINPASS
          value: changemeplease
        - name: DATABASE_URL
          value: mysql://kimai:kimai@kimai-mysql/kimai?charset=utf8mb4
    extraVolumes:
        - accessMode: ReadWriteOnce
          accessModes:
              - ReadWriteOnce
          emptyDir: false
          mountPath: /opt/kimai/var/data
          name: kimai-data-volume
          size: 1Gi
          storageClass: standard
        - accessMode: ReadWriteOnce
          accessModes:
              - ReadWriteOnce
          emptyDir: false
          mountPath: /opt/kimai/var/plugins
          name: kimai-plugins-volume
          size: 1Gi
          storageClass: standard
    cronjobs: []
    addons:
        - displayName: MySQL
          env: []
          icon: /img/addons/mysql.svg
          id: kubero-operator
          kind: KuberoMysql
          resourceDefinitions:
              KuberoMysql:
                  apiVersion: application.kubero.dev/v1alpha1
                  kind: KuberoMysql
                  metadata:
                      name: kimai-mysql
                  spec:
                      mysql:
                          auth:
                              createDatabase: true
                              database: kimai
                              password: kimai
                              rootPassword: kimai
                              username: kimai
                          global:
                              storageClass: standard
                          primary:
                              persistence:
                                  accessModes:
                                      - ReadWriteOnce
                                  size: 1Gi
          version:
              latest: 0.1.5
    web:
        replicaCount: 1
    worker:
        replicaCount: 0
    image:
        containerPort: "8001"
        pullPolicy: Always
        repository: kimai/kimai2
        tag: apache
