name: whoogle
description: 'Whoogle is a self-hosted, ad-free, privacy-respecting metasearch engine.'
tags:
- Search
source: https://github.com/benbusby/whoogle-search
website: https://github.com/benbusby/whoogle-search
icon: https://www.freeiconspng.com/uploads/question-answer-icon-14.png
screenshots:
- https://raw.githubusercontent.com/benbusby/whoogle-search/main/docs/screenshot_desktop.png
- https://raw.githubusercontent.com/benbusby/whoogle-search/main/docs/screenshot_mobile.png