apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
    name: presentator
    annotations:
        kubero.dev/template.architecture: "[]"
        kubero.dev/template.description: ""
        kubero.dev/template.icon: ""
        kubero.dev/template.installation: ""
        kubero.dev/template.links: "[]"
        kubero.dev/template.screenshots: "[]"
        kubero.dev/template.source: "https://github.com/presentator/presentator"
        kubero.dev/template.tags: "['design', 'collaboration', 'prototyping', 'ui', 'ux']"
        kubero.dev/template.title: ""
        kubero.dev/template.website: ""
    labels:
        manager: kubero
spec:
    name: presentator
    deploymentstrategy: docker
    envVars: []
    extraVolumes:
        - accessMode: ReadWriteOnce
          accessModes:
              - ReadWriteOnce
          emptyDir: false
          mountPath: /pr/pb_data
          name: presentator-volume
          size: 1Gi
          storageClass: standard
    cronjobs: []
    addons: []
    web:
        replicaCount: 1
    worker:
        replicaCount: 0
    image:
        containerPort: 8080
        pullPolicy: Always
        repository: ganigeorgiev/presentator
        tag: latest
