apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: joomla
spec:
  name: joomla
  deploymentstrategy: docker
  image:
    repository: joomla
    tag: latest
    containerPort: "80"
  addons:
  - displayName: Kubero Postgresql
    env: []
    icon: /img/addons/postgresql.png
    id: kubero-operator
    kind: KuberoPostgresql
    resourceDefinitions:
      KuberoPostgresql:
        apiVersion: application.kubero.dev/v1alpha1
        kind: KuberoPostgresql
        metadata:
          name: joomla-postgresql
        spec:
          postgresql:
            global:
              postgresql:
                auth:
                  database: postgresql
                  password: joomla
                  postgresPassword: joomla
                  username: joomla
              storageClass: standard
            primary:
              persistence:
                size: 1Gi
  envVars:
  - name: JOOMLA_DB_HOST
    value: joomla-mysql
  - name: JOOMLA_DB_PASSWORD
    value: joomla
  cronjobs: []
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /var/www/html
    name: joomla-volume
    size: 1Gi
    storageClass: standard
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /var/run/apache2
    name: joomla-rundir
    size: 1Mi
    storageClass: standard
  web:
    replicaCount: 1
  worker:
    replicaCount: 0