apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
    name: metube
    labels:
        manager: kubero
spec:
    name: metube
    deploymentstrategy: docker
    envVars: []
    extraVolumes:
        - accessMode: ReadWriteOnce
          accessModes:
              - ReadWriteOnce
          emptyDir: false
          mountPath: /downloads
          name: downloads-volume
          size: 10Gi
    cronjobs: []
    addons: []
    web:
        replicaCount: 1
    worker:
        replicaCount: 0
    image:
        containerPort: "8081"
        pullPolicy: Always
        repository: ghcr.io/alexta69/metube
        tag: latest