apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: vaultwarden
spec:
  name: vaultwarden
  domain: vaultwarden.lacolhost.com
  deploymentstrategy: docker
  image:
    repository: vaultwarden/server
    tag: latest
    containerPort: "80"
  ingress:
    hosts:
    - host: vaultwarden.lacolhost.com
      paths:
      - path: /
        pathType: ImplementationSpecific
  addons: []
  envVars: []
  cronjobs: []
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /data
    name: vaultwarden-data
    size: 1Gi
    storageClass: standard
  web:
    replicaCount: 1
  worker:
    replicaCount: 0