name: Atuin
description: 'Atuin replaces your existing shell history with a SQLite database, and records additional context for your commands.'
tags:
- administration
source: https://github.com/atuinsh/atuin
website: https://atuin.sh/
icon: https://avatars.githubusercontent.com/u/122059230?s=200&v=4
screenshots:
- https://raw.githubusercontent.com/atuinsh/atuin/main/demo.gif