apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: typesense
spec:
  name: typesense
  deploymentstrategy: docker
  image:
    repository: typesense/typesense
    tag: latest
    containerPort: "8108"
  addons: []
  envVars:
    - name: TYPESENSE_API_KEY
      value: "your-api-key" # Replace with your actual API key
    - name: TYPESENSE_DATA_DIR
      value: "/data"
  cronjobs: []
  extraVolumes:
    - accessModes:
      - ReadWriteOnce
      emptyDir: false
      mountPath: /data
      name: typesense-data
      size: 1Gi
      storageClass: standard
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
