apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
    name: kener
spec:
    name: kener
    deploymentstrategy: docker
    envVars:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
    extraVolumes:
          mountPath: /config
          name: kener-volume
          size: 1Gi
    cronjobs: []
    addons: []
    web:
        replicaCount: 1
    image:
        containerPort: "3000"
        pullPolicy: Always
        repository: rajnandan1/kener
        tag: latest
