name: Kener
description: 'Kener is a Modern Self hosted Status Page'
tags:
- monitoring
source: https://github.com/rajnandan1/kener
website: https://www.kener.ing
icon: https://kener.ing/logo.png
screenshots:
- https://camo.githubusercontent.com/8d4f2ea8ac5a6200ad87e39a21be25c5b279d540a886db131a076ef69227ca7a/68747470733a2f2f6b656e65722e696e672f73732e706e67