name: Lychee
description: 'An easy-to-use photo-management-system to manage and share photos.'
tags:
- Search
source: https://github.com/LycheeOrg/Lychee
website: https://lycheeorg.github.io/
icon: https://avatars.githubusercontent.com/u/37916028?s=200&v=4
screenshots:
- https://lycheeorg.github.io/assets/3.BzY-5hAj.jpg