name: Activepieces
description: 'Your friendliest open source all-in-one automation tool ✨ Workflow automation tool 100+ integration / Enterprise automation tool / Zapier Alternative'
tags:
- Workflow
- Automation
- low-code
- no-code
source: https://github.com/activepieces/activepieces
website: https://www.activepieces.com/
icon: https://avatars.githubusercontent.com/u/99494700?s=200&v=4
screenshots:
- https://github.com/activepieces/activepieces/assets/1812998/e75616ce-7801-45b7-b3fa-eba778bebde3