apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
    name: kubectl
spec:
    name: kubectl
    deploymentstrategy: docker
    envVars: []
    extraVolumes: []
    cronjobs: []
    addons: []
    web:
        replicaCount: 1
    worker:
        replicaCount: 0
    image:
        containerPort: 8080
        repository: kubeoperator/webkubectl
        tag: latest