name: Casdoor
description: 'An Identity and Access Management (IAM) / Single-Sign-On (SSO) platform with beautiful web UI and the official client SDKs'
tags:
- authentication
source: https://github.com/casdoor/casdoor
website: https://casdoor.org
icon: https://avatars.githubusercontent.com/u/72992104?s=200&v=4
screenshots:
- https://casdoor.org/assets/images/import_success-8be0db7efa60235af1149e529292948b.png
- https://casdoor.org/assets/images/dashboard-951aa5187e74f5446a91447e00111c79.png
- https://casdoor.org/assets/images/step4_result2-5f31450f52b9f797c8f1afcf2fd19914.png