apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: planning-poker
spec:
  name: planning-poker
  deploymentstrategy: docker
  image:
    repository: axeleroy/self-host-planning-poker
    tag: latest
    containerPort: "8000"
  addons: []
  envVars: []
  cronjobs: []
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /data
    name: planning-poker-volume
    size: 1Gi
    storageClass: default
  web:
    replicaCount: 1
  worker:
    replicaCount: 0