apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
    name: qdrant
    annotations:
        kubero.dev/template.architecture: "[]"
        kubero.dev/template.description: "High-performance, massive-scale Vector Database and Vector Search Engine for the next generation of AI. Also available in the cloud"
        kubero.dev/template.icon: "https://avatars.githubusercontent.com/u/73504361"
        kubero.dev/template.installation: ""
        kubero.dev/template.links: "[]"
        kubero.dev/template.screenshots: "[]"
        kubero.dev/template.source: "https://github.com/qdrant/qdrant"
        kubero.dev/template.categories: '["database"]'
        kubero.dev/template.title: "qdrant"
        kubero.dev/template.website: "https://qdrant.tech/"
    labels:
        manager: kubero
spec:
    name: qdrant
    deploymentstrategy: docker
    envVars: []
    extraVolumes:
        - accessMode: ReadWriteOnce
          accessModes:
              - ReadWriteOnce
          emptyDir: false
          mountPath: /qdrant/storage
          name: qdrant-volume
          size: 1Gi
          storageClass: standard
    cronjobs: []
    addons: []
    web:
        replicaCount: 1
    worker:
        replicaCount: 0
    image:
        containerPort: "6333"
        pullPolicy: Always
        repository: qdrant/qdrant
        tag: latest
