apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
    name: piwigo
    annotations:
        kubero.dev/template.architecture: '["linux/amd64", "linux/arm64"]'
        kubero.dev/template.description: "Manage your photos with Piwigo, a full featured open source photo gallery application for the web."
        kubero.dev/template.icon: "https://avatars.githubusercontent.com/u/9326886"
        kubero.dev/template.installation: "This app requires a manual step to configure the MySQL database."
        kubero.dev/template.links: "[]"
        kubero.dev/template.screenshots: '["https://piwigo.org/plugins/piwigo-piwigodotorg//images/home/responsive-screens.png"]'
        kubero.dev/template.source: "https://github.com/Piwigo/Piwigo"
        kubero.dev/template.categories: '["utilities"]'
        kubero.dev/template.title: "Piwigo"
        kubero.dev/template.website: "https://piwigo.org/"
    labels:
        manager: kubero
spec:
    name: piwigo
    deploymentstrategy: docker
    envVars: []
    extraVolumes:
        - accessMode: ReadWriteOnce
          accessModes:
              - ReadWriteOnce
          emptyDir: false
          mountPath: /config
          name: piwigo-config-volume
          size: 1Gi
          storageClass: standard
        - accessMode: ReadWriteOnce
          accessModes:
              - ReadWriteOnce
          emptyDir: false
          mountPath: /gallery
          name: piwigo-gallery-volume
          size: 1Gi
          storageClass: standard
    cronjobs: []
    addons:
        - displayName: MySQL
          env: []
          icon: /img/addons/mysql.svg
          id: kubero-operator
          kind: KuberoMysql
          resourceDefinitions:
              KuberoMysql:
                  apiVersion: application.kubero.dev/v1alpha1
                  kind: KuberoMysql
                  metadata:
                      name: piwigo-mysql
                  spec:
                      mysql:
                          auth:
                              createDatabase: true
                              database: piwigo
                              password: piwigo
                              rootPassword: piwigo
                              username: piwigo
                          global:
                              storageClass: standard
                          primary:
                              persistence:
                                  accessModes:
                                      - ReadWriteOnce
                                  size: 1Gi
          version:
              latest: 0.1.5
    web:
        replicaCount: 1
    worker:
        replicaCount: 0
    image:
        containerPort: "80"
        pullPolicy: Always
        repository: lscr.io/linuxserver/piwigo
        tag: latest
