name: Ryot
description: 'A self hosted platform for tracking various facets of your life - media, fitness etc.'
tags:
- metrics
source: https://github.com/ignisda/ryot
website: https://github.com/ignisda/ryot
icon: https://avatars.githubusercontent.com/u/60938164?v=4
screenshots: