apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
    name: evershop
    labels:
        manager: kubero
spec:
    name: evershop
    deploymentstrategy: docker
    envVars:
        - name: DB_HOST
          value: evershop-postgresql
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: postgresql
        - name: DB_USER
          value: evershop
        - name: DB_PASSWORD
          value: postgres
    extraVolumes: []
    cronjobs: []
    addons:
        - displayName: Postgresql
          env: []
          icon: /img/addons/postgresql.png
          id: kubero-operator
          kind: KuberoPostgresql
          resourceDefinitions:
              KuberoPostgresql:
                  apiVersion: application.kubero.dev/v1alpha1
                  kind: KuberoPostgresql
                  metadata:
                      name: evershop-postgresql
                  spec:
                      postgresql:
                          global:
                              postgresql:
                                  auth:
                                      database: postgresql
                                      password: postgres
                                      postgresPassword: postgres
                                      username: evershop
                              storageClass: standard
                          primary:
                              persistence:
                                  size: 1Gi
          version:
              latest: 0.1.2
    web:
        replicaCount: 1
    worker:
        replicaCount: 0
    image:
        containerPort: "3000"
        pullPolicy: Always
        repository: evershop/evershop
        tag: latest
