apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: gatus
spec:
  name: gatus
  domain: gatus.lacolhost.com
  deploymentstrategy: docker
  image:
    repository: twinproduction/gatus
    tag: latest
    containerPort: "8080"
  ingress:
    hosts:
    - host: gatus.lacolhost.com
      paths:
      - path: /
        pathType: ImplementationSpecific
  addons: []
  envVars: []
  cronjobs: []
  extraVolumes: []
  web:
    replicaCount: 1
  worker:
    replicaCount: 0