name: Rocket.Chat
description: 'Rocket.Chat is an open-source fully customizable communications platform developed in JavaScript for organizations with high standards of data protection.'
tags:
- communications
source: https://github.com/RocketChat/Rocket.Chat
website: https://rocket.chat/
icon: https://avatars.githubusercontent.com/u/12508788?s=200&v=4
screenshots:
- https://global-uploads.webflow.com/611a19b9853b7414a0f6b3f6/6464d93d33af48db33864025_Team%20Collab.webp
- https://global-uploads.webflow.com/611a19b9853b7414a0f6b3f6/615d85d3d3ae5682e8571dfb_Group%203924%20(1).png