apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
    name: textbee-api
    annotations:
        kubero.dev/template.architecture: '["amd64", "arm64"]'
        kubero.dev/template.description: "textbee.dev is an opensource and free sms-gatway for sending SMS messages through API or dashboard web interface."
        kubero.dev/template.icon: "https://avatars.githubusercontent.com/u/38871878"
        kubero.dev/template.installation: ""
        kubero.dev/template.links: "[]"
        kubero.dev/template.screenshots: "[]"
        kubero.dev/template.source: "https://github.com/vernu/textbee"
        kubero.dev/template.categories: '["notification"]'
        kubero.dev/template.title: "Textbee API"
        kubero.dev/template.website: "https://textbee.dev/"
    labels:
        manager: kubero
spec:
    name: textbee-api
    deploymentstrategy: docker
    envVars:
        - name: JWT_SECRET
          value: random32
        - name: JWT_EXPIRATION
          value: 60d
        - name: FRONTEND_URL
          value: https://textbee.localhost
        - name: MONGO_URI
          value: mongodb://textbee:textbee@textbee-api-mongodb:27017/textbee
        - name: FIREBASE_PROJECT_ID
          value: ""
        - name: FIREBASE_PRIVATE_KEY_ID
          value: ""
        - name: FIREBASE_PRIVATE_KEY
          value: ""
        - name: FIREBASE_CLIENT_EMAIL
          value: ""
        - name: FIREBASE_CLIENT_ID
          value: ""
        - name: FIREBASE_CLIENT_C509_CERT_URL
          value: ""
    extraVolumes: []
    cronjobs: []
    addons:
        - displayName: MongoDB
          env: []
          icon: /img/addons/mongo.svg
          id: kubero-operator
          kind: KuberoMongoDB
          resourceDefinitions:
              KuberoMongoDB:
                  apiVersion: application.kubero.dev/v1alpha1
                  kind: KuberoMongoDB
                  metadata:
                      name: textbee-api-mongodb
                  spec:
                      mongodb:
                          architecture: standalone
                          auth:
                              databases:
                                  - textbee
                              passwords:
                                  - textbee
                              rootPassword: textbee
                              rootUser: root
                              usernames:
                                  - textbee
                          directoryPerDB: true
                          disableJavascript: false
                          global:
                              storageClass: standard
                          persistence:
                              size: 1Gi
                          replicaCount: 1
          version:
              latest: 0.1.8
    web:
        replicaCount: 1
    worker:
        replicaCount: 0
    image:
        containerPort: 8080
        pullPolicy: Always
        repository: ghcr.io/vernu/textbee/api
        tag: latest
