apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: dashy
spec:
  name: dashy
  deploymentstrategy: docker
  image:
    repository: lissy93/dashy
    tag: latest
    containerPort: "8080"
  addons: []
  envVars:
  - name: NODE_ENV
    value: production
  cronjobs: []
  extraVolumes: []
  web:
    replicaCount: 1
  worker:
    replicaCount: 0