name: AFFiNE
description: 'AFFiNE is a next-gen knowledge base that brings planning, sorting and creating all together'
tags:
- drawing
- planning
- collaboration
source: https://github.com/toeverything/AFFiNE
website: https://affine.pro/
documentation: 
- https://docs.affine.pro/docs/hello-bonjour-aloha-%E4%BD%A0%E5%A5%BD
icon: https://raw.githubusercontent.com/toeverything/AFFiNE.pro/60f42504c0e1572a2ede0a8d95a398a229b0bb9a/public/overview/stay-focused-logo.png
screenshots:
- https://private-user-images.githubusercontent.com/79301703/307680139-49a426bb-8d2b-4216-891a-fa5993642253.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNzcyMDAsIm5iZiI6MTcxMjE3NjkwMCwicGF0aCI6Ii83OTMwMTcwMy8zMDc2ODAxMzktNDlhNDI2YmItOGQyYi00MjE2LTg5MWEtZmE1OTkzNjQyMjUzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDIwNDE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2M2I0YTQwNTY3YzgxZmEyNTFhMTM4YmI5ZDU4OWE2NDJlYTkxYzEzZDBmODc1MDc0NDE3ZWY2MDQwNDVhN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9oOyNezYiBvn4ArmSuai3I0HGqwr1HtaWKVKbiNcw48