apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: shiori
spec:
  name: shiori
  deploymentstrategy: docker
  image:
    repository: ghcr.io/go-shiori/shiori
    tag: latest
    containerPort: "8080"
  addons: []
  envVars: []
  cronjobs: []
  extraVolumes: []
  web:
    replicaCount: 1
  worker:
    replicaCount: 0