name: Traggo
description: 'Traggo is a self-hosted time tracking tool. It is designed to be
  easy to use and to be self-hosted. It is written in Go and uses Vue.js for the
  frontend. '
tags:
- time tracking
- time management
source: https://github.com/traggo/server
website: https://traggo.org
icon: https://raw.githubusercontent.com/traggo/logo/master/logo.png
screenshots:
- https://github.com/traggo/server/raw/master/.github/traggo_list.png
- https://github.com/traggo/server/raw/master/.github/traggo_calendar.png
- https://github.com/traggo/server/raw/master/.github/traggo_dashboard.png