apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
    name: whiteboard
    labels:
        manager: kubero
spec:
    name: whiteboard
    deploymentstrategy: docker
    envVars: []
    extraVolumes: []
    cronjobs: []
    addons: []
    web:
        replicaCount: 1
    worker:
        replicaCount: 0
    image:
        containerPort: 8080
        pullPolicy: Always
        repository: rofl256/whiteboard
        tag: latest
