name: TimeTagger
description: 'TimeTagger is a simple time tracking tool for your terminal.'
tags:
- Time tracking
source: https://github.com/almarklein/timetagger
website: https://timetagger.app/
icon: https://timetagger.app/timetagger_sl.svg
screenshots:
- https://timetagger.app/screenshot1.png
- https://timetagger.app/screenshot2.png
- https://timetagger.app/screenshot3.png