apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
    name: phpmyadmin
    labels:
        manager: kubero
spec:
    name: phpmyadmin
    deploymentstrategy: docker
    envVars:
        - name: PMA_ABSOLUTE_URI
          value: https://phpmyadmin.localhost
        - name: PMA_ARBITRARY
          value: "1"
        - name: TZ
          value: Europe/Berlin
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
    extraVolumes: []
    cronjobs: []
    addons: []
    web:
        replicaCount: 1
    worker:
        replicaCount: 0
    image:
        containerPort: "80"
        pullPolicy: Always
        repository: lscr.io/linuxserver/phpmyadmin
        tag: latest