apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: phpmyadmin
spec:
  name: phpmyadmin
  deploymentstrategy: docker
  image:
    repository: ghcr.io/kubero-dev/phpmyadmin
    tag: latest
    containerPort: "8080"
  addons: []
  envVars:
  - name: PMA_HOST
    value: myservice-mysql
  - name: PMA_PORT
    value: "3306"
  - name: PMA_BLOWFISH_SECRET
    value: dfdfasdfpdppfpasdf
  cronjobs: []
  extraVolumes: []
  web:
    replicaCount: 1
  worker:
    replicaCount: 0