name: trilium
description: 'Trilium Notes is a hierarchical note taking application with focus
  on building large personal knowledge bases. '
tags:
- note taking
- knowledge base
source: https://github.com/zadam/trilium
website: https://github.com/zadam/trilium
icon: https://github.com/zadam/trilium/blob/master/images/app-icons/png/256x256.png
screenshots:
- https://raw.githubusercontent.com/wiki/zadam/trilium/images/screenshot.png
