apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  labels:
    manager: kubero
  name: memos
spec:
  name: memos
  domain: memos.lacolhost.com
  deploymentstrategy: docker
  image:
    repository: neosmemo/memos
    tag: latest
    containerPort: "5230"
  ingress:
    hosts:
    - host: memos.lacolhost.com
      paths:
      - path: /
        pathType: ImplementationSpecific
  addons: []
  envVars: []
  cronjobs: []
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /var/opt/memos
    name: memos-data
    size: 1Gi
    storageClass: standard
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
