name: memos
description: 'Memos is a simple note taking app. '
tags:
- note taking
source: https://github.com/usememos/memos
website: https://usememos.com/
icon: https://usememos.com/logo.png
screenshots:
- https://github.com/usememos/memos/raw/main/resources/demo.webp
