apiVersion: "alpha.keroku.com/v1alpha"
kind: Application
metadata:
  name: my-new-app-example
spec:
  appName: my-awesome-app
  stack: alpine-latest
  framework: nodejs
  gitrepo: example-org/my-awesome-app