apiVersion: "kubero.dev/v1alpha1"
kind: Pipeline
metadata:
  name: my-new-pipeline-example
  labels: 
    manager: 'kubero'
spec:
  name: my-awesome-app
  reviewapps: true
  gitrepo: https://github.com/kubero-dev/template-nodeapp.git
  phases:
    - name: test
      enabled: true
    - name: stage
      enabled: false
    - name: production
      enabled: false