apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  creationTimestamp: "2023-01-18T10:46:34Z"
  finalizers:
  - helm.sdk.operatorframework.io/uninstall-release
  generation: 9
  labels:
    manager: kubero
  name: wp
  namespace: test-stage
  resourceVersion: "1395125"
  uid: 779a8006-827e-4d1b-8aea-62088f5f069a
spec:
  addons:
  - displayName: Kubero Mysql
    env: []
    icon: /img/addons/MySQL.png
    id: kubero-operator
    kind: KuberoMysql
    resourceDefinitions:
      KuberoMysql:
        apiVersion: application.kubero.dev/v1alpha1
        kind: KuberoMysql
        metadata:
          name: mysql2
        spec:
          mysql:
            auth:
              createDatabase: true
              database: wordpress
              password: wordpress
              rootPassword: wordpress
              username: wordpress
            global:
              storageClass: standard
            primary:
              persistence:
                accessModes:
                - ReadWriteOnce
                size: 1Gi
    version:
      installed: 0.0.93
      latest: 0.0.93
  affinity: {}
  autodeploy: true
  autoscale: false
  autoscaling:
    enabled: false
  branch: main
  buildpack: NodeJS
  cronjobs: []
  deploymentstrategy: docker
  domain: wp.lacolhost.com
  envVars:
  - name: WORDPRESS_DATABASE_HOST
    value: mysql2
  - name: WORDPRESS_DATABASE_USER
    value: wordpress
  - name: WORDPRESS_DATABASE_PASSWORD
    value: wordpress
  - name: WORDPRESS_DATABASE_NAME
    value: wordpress
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /bitnami/wordpress
    name: wordpress-data
    size: 1Gi
    storageClass: standard
  fullnameOverride: ""
  gitrepo:
    admin: true
    clone_url: https://github.com/kubero-dev/template-nodeapp.git
    default_branch: main
    description: Simple example Node app
    homepage: ""
    id: 501665730
    language: JavaScript
    name: template-nodeapp
    node_id: R_kgDOHebPwg
    owner: kubero-dev
    private: false
    push: true
    ssh_url: git@github.com:kubero-dev/template-nodeapp.git
    visibility: public
  image:
    build:
      command: npm install
      repository: node
      tag: latest
    containerPort: 8080
    fetch:
      repository: ghcr.io/kubero-dev/buildpacks/fetch
      tag: main
    pullPolicy: Always
    repository: docker.io/bitnami/wordpress
    run:
      command: node index.js
      repository: node
      securityContext:
        readOnlyRootFilesystem: false
      tag: latest
    tag: latest
  imagePullSecrets: []
  ingress:
    annotations: {}
    className: ""
    enabled: true
    hosts:
    - host: wp.lacolhost.com
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls: []
  name: wp
  nameOverride: ""
  nodeSelector: {}
  phase: stage
  pipeline: test
  podAnnotations: {}
  podSecurityContext: {}
  podsize:
    default: true
    description: 'Small (CPU: 0.25, Memory: 0.5Gi)'
    name: small
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 0.5Gi
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 0.5Gi
  service:
    port: 80
    type: ClusterIP
  serviceAccount:
    annotations: {}
    create: true
    name: ""
  tolerations: []
  web:
    autoscaling:
      maxReplicas: 3
      minReplicas: 1
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
    replicaCount: 1
  worker:
    autoscaling:
      maxReplicas: 0
      minReplicas: 0
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
    replicaCount: 0
status:
  conditions:
  - lastTransitionTime: "2023-01-18T10:46:34Z"
    status: "True"
    type: Initialized
  - lastTransitionTime: "2023-01-18T10:49:00Z"
    message: |
      1. Get the application URL by running these commands:
        http://wp.lacolhost.com/
    reason: UpgradeSuccessful
    status: "True"
    type: Deployed
  deployedRelease:
    manifest: |
      ---
      # Source: kuberoapp/templates/serviceaccount.yaml
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: wp-kuberoapp
        labels:
          helm.sh/chart: kuberoapp-0.1.0
          app.kubernetes.io/name: kuberoapp
          app.kubernetes.io/instance: wp
          app.kubernetes.io/version: "1.16.0"
          app.kubernetes.io/managed-by: Helm
      ---
      # Source: kuberoapp/templates/pvc.yaml
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: wordpress-data
      spec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      ---
      # Source: kuberoapp/templates/service.yaml
      apiVersion: v1
      kind: Service
      metadata:
        name: wp-kuberoapp
        labels:
          helm.sh/chart: kuberoapp-0.1.0
          app.kubernetes.io/name: kuberoapp
          app.kubernetes.io/instance: wp
          app.kubernetes.io/version: "1.16.0"
          app.kubernetes.io/managed-by: Helm
      spec:
        type: ClusterIP
        ports:
          - port: 80
            targetPort: http
            protocol: TCP
            name: http
        selector:
          app.kubernetes.io/name: kuberoapp
          app.kubernetes.io/instance: wp-web
      ---
      # Source: kuberoapp/templates/deployment-web.yaml
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: wp-kuberoapp-web
        labels:
          helm.sh/chart: kuberoapp-0.1.0
          app.kubernetes.io/name: kuberoapp
          app.kubernetes.io/instance: wp
          app.kubernetes.io/version: "1.16.0"
          app.kubernetes.io/managed-by: Helm
      spec:
        replicas: 1
        selector:
          matchLabels:
            app.kubernetes.io/name: kuberoapp
            app.kubernetes.io/instance: wp-web
        template:
          metadata:
            labels:
              app.kubernetes.io/name: kuberoapp
              app.kubernetes.io/instance: wp-web
          spec:
            serviceAccountName: wp-kuberoapp
            securityContext:
              {}
            containers:
              - name: kuberoapp-web
                securityContext:
                  readOnlyRootFilesystem: false
                image: "docker.io/bitnami/wordpress:latest"
                imagePullPolicy: Always
                env:
                  - name: PROC_TYPE
                    value: web
                  - name: PORT
                    value: "8080"
                  - name: WORDPRESS_DATABASE_HOST
                    value: mysql2
                  - name: WORDPRESS_DATABASE_USER
                    value: wordpress
                  - name: WORDPRESS_DATABASE_PASSWORD
                    value: wordpress
                  - name: WORDPRESS_DATABASE_NAME
                    value: wordpress
                ports:
                  - name: http
                    containerPort: 8080
                    protocol: TCP
                livenessProbe:
                  httpGet:
                    path: /
                    port: http
                readinessProbe:
                  httpGet:
                    path: /
                    port: http
                volumeMounts:
                  - mountPath: /tmp
                    name: tmp-storage
                    readOnly: false
                  - mountPath: /bitnami/wordpress
                    name: wordpress-data
                resources:
                  limits:
                    cpu: 500m
                    memory: 1Gi
                  requests:
                    cpu: 250m
                    memory: 0.5Gi
            volumes:
            - name: deployment-keys
              secret:
                defaultMode: 0600
                secretName: deployment-keys
            - name: app-storage
              emptyDir: {}
            - name: tmp-storage
              emptyDir: {}
            - name: wordpress-data
              persistentVolumeClaim:
                claimName: wordpress-data
      ---
      # Source: kuberoapp/templates/deployment-worker.yaml
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: wp-kuberoapp-worker
        labels:
          helm.sh/chart: kuberoapp-0.1.0
          app.kubernetes.io/name: kuberoapp
          app.kubernetes.io/instance: wp
          app.kubernetes.io/version: "1.16.0"
          app.kubernetes.io/managed-by: Helm
      spec:
        replicas: 0
        selector:
          matchLabels:
            app.kubernetes.io/name: kuberoapp
            app.kubernetes.io/instance: wp-worker
        template:
          metadata:
            labels:
              app.kubernetes.io/name: kuberoapp
              app.kubernetes.io/instance: wp-worker
          spec:
            serviceAccountName: wp-kuberoapp
            securityContext:
              {}
            containers:
              - name: kuberoapp-worker
                securityContext:
                  readOnlyRootFilesystem: false
                image: "docker.io/bitnami/wordpress:latest"
                imagePullPolicy: Always
                env:
                  - name: PROC_TYPE
                    value: worker
                  - name: PORT
                    value: "8080"
                  - name: WORDPRESS_DATABASE_HOST
                    value: mysql2
                  - name: WORDPRESS_DATABASE_USER
                    value: wordpress
                  - name: WORDPRESS_DATABASE_PASSWORD
                    value: wordpress
                  - name: WORDPRESS_DATABASE_NAME
                    value: wordpress
                ports:
                  - name: http
                    containerPort: 8080
                    protocol: TCP
                volumeMounts:
                  - mountPath: /tmp
                    name: tmp-storage
                    readOnly: false
                  - mountPath: /bitnami/wordpress
                    name: wordpress-data
                resources:
                  limits:
                    cpu: 500m
                    memory: 1Gi
                  requests:
                    cpu: 250m
                    memory: 0.5Gi
            volumes:
            - name: deployment-keys
              secret:
                defaultMode: 0600
                secretName: deployment-keys
            - name: app-storage
              emptyDir: {}
            - name: tmp-storage
              emptyDir: {}
            - name: wordpress-data
              persistentVolumeClaim:
                claimName: wordpress-data
      ---
      # Source: kuberoapp/templates/ingress.yaml
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: wp-kuberoapp
        labels:
          helm.sh/chart: kuberoapp-0.1.0
          app.kubernetes.io/name: kuberoapp
          app.kubernetes.io/instance: wp
          app.kubernetes.io/version: "1.16.0"
          app.kubernetes.io/managed-by: Helm
      spec:
        rules:
          - host: "wp.lacolhost.com"
            http:
              paths:
                - path: /
                  pathType: ImplementationSpecific
                  backend:
                    service:
                      name: wp-kuberoapp
                      port:
                        number: 80
      ---
      # Source: kuberoapp/templates/addons.yaml
      apiVersion: application.kubero.dev/v1alpha1
      kind: KuberoMysql
      metadata:
        name: mysql2
      spec:
        mysql:
          auth:
            createDatabase: true
            database: wordpress
            password: wordpress
            rootPassword: wordpress
            username: wordpress
          global:
            storageClass: standard
          primary:
            persistence:
              accessModes:
              - ReadWriteOnce
              size: 1Gi
    name: wp
