name: Slink
description: 'Self-hosted image sharing service.'
tags:
- images
- gallery
- sharing
source: https://github.com/andrii-kryvoviaz/slink
website: https://github.com/andrii-kryvoviaz/slink
icon: https://raw.githubusercontent.com/andrii-kryvoviaz/slink/main/client/static/favicon.png
screenshots:
- https://github.com/andrii-kryvoviaz/slink/raw/main/screens/e98ea79e-01bb-4e23-98ba-b18841d09c9b.png