name: LimeSurvey
description: LimeSurvey is the simple, quick and anonymous online survey tool that's bursting with juicy insights.
tags:
- survel
source: https://github.com/LimeSurvey/LimeSurvey
website: https://www.limesurvey.org
icon: https://avatars.githubusercontent.com/u/1364105?s=200&v=4
documentation: https://manual.limesurvey.org/LimeSurvey_Manual
screenshots:
- https://manual.limesurvey.org/images/1/15/Surveys-alternative_button.png
- https://manual.limesurvey.org/images/5/50/Newsurveyscreen.png