apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: homebox
spec:
  name: homebox
  domain: homebox.lacolhost.com
  deploymentstrategy: docker
  image:
    repository: ghcr.io/hay-kot/homebox
    tag: latest
    containerPort: "7745"
  ingress:
    hosts:
    - host: homebox.lacolhost.com
      paths:
      - path: /
        pathType: ImplementationSpecific
  addons: []
  envVars: []
  cronjobs: []
  extraVolumes:
  - accessModes:
    - ReadWriteMany
    emptyDir: false
    mountPath: /data
    name: homebox-data
    size: 1Gi
    storageClass: standard
  web:
    replicaCount: 1
  worker:
    replicaCount: 0