name: ChartDB
description: A database diagrams editor to visualize and design your DB with a single query.
tags:
- administration
- database
source: https://github.com/chartdb/chartdb
website: https://chartdb.io/
icon: https://avatars.githubusercontent.com/u/177466511?s=200&v=4
screenshots:
- https://raw.githubusercontent.com/chartdb/chartdb/main/public/chartdb.png