apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
    name: pairdrop
    annotations:
        kubero.dev/template.architecture: '["linux/amd64", "linux/arm64"]'
        kubero.dev/template.description: "PairDrop: Transfer Files Cross-Platform. No Setup, No Signup."
        kubero.dev/template.icon: "https://avatars.githubusercontent.com/u/52242352"
        kubero.dev/template.installation: ""
        kubero.dev/template.links: "[]"
        kubero.dev/template.screenshots: "[]"
        kubero.dev/template.source: "https://github.com/schlagmichdoch/PairDrop"
        kubero.dev/template.categories: '["productivity", "work"]'
        kubero.dev/template.title: "PairDrop"
        kubero.dev/template.website: "https://pairdrop.net/"
    labels:
        manager: kubero
spec:
    name: pairdrop
    deploymentstrategy: docker
    envVars:
        - name: WS_FALLBACK
          value: "false"
        - name: DEBUG_MODE
          value: "false"
        - name: RATE_LIMIT
          value: "false"
        - name: TZ
          value: "Etc/UTC"
    extraVolumes: []
    cronjobs: []
    addons: []
    web:
        replicaCount: 1
    worker:
        replicaCount: 0
    image:
        containerPort: "3000"
        pullPolicy: Always
        repository: lscr.io/linuxserver/pairdrop
        tag: latest
