name: 'Jest Codecov'
on:
  workflow_dispatch:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: ./server
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4         # checkout the repo
      - name: Install dependencies        # install dependencies
        run: yarn install --frozen-lockfile
      - run: yarn build                   # install packages
      - run: yarn test                    # run tests (configured to use jest-junit reporter)
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: server/coverage
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}