name: 'Mail on Star'
on:
  workflow_dispatch:
  watch:
    types: [started]
jobs:
  stargazer:
    name: 'stargazers'
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v1.3.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_PASS }}
          subject: ${{ github.event.repository.stargazers_count }} ✨ ${{ github.actor }} stared ${{ github.repository }}
          body: | 
            ${{ github.actor }} just starred your mail-on-star repo!!! 
            ${{ github.event.repository.html_url }}
            Forks: ${{ github.event.repository.forks_count }}
            Stars: ${{ github.event.repository.stargazers_count }}
            Issues: ${{ github.event.repository.open_issues_count }}
            
            ${{ github.repository }}
          to: ${{ secrets.GMAIL_ADDRESS }}
          from: ${{ secrets.GMAIL_ADDRESS }}