name: 'Yamllint services'
on:
  pull_request:
    paths:
      - 'services/**'
jobs:
  yamllint:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Yamllint services'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: 'services'
          yamllint_config_datapath: 'services/.yamllint'
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}